[package]
name = "use-accessibility-check"
description = "Primitive accessibility issue filtering helpers"
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
documentation = "https://docs.rs/use-accessibility-check"
keywords = ["accessibility", "issue", "severity", "check"]
categories = ["algorithms", "science"]

[lints]
workspace = true