[package]
name = "use-motion-preference"
description = "Primitive reduced-motion preference helpers"
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
documentation = "https://docs.rs/use-motion-preference"
keywords = ["accessibility", "motion", "animation", "preference"]
categories = ["algorithms", "science"]

[lints]
workspace = true